#!/usr/bin/env bash

# Check user environment variable
if [[ -z "${GCLOUD_PROJECT_ID}" ]]; then
  echo "Missing GCLOUD_PROJECT_ID environment variable" >&2
  exit 1
fi

# Config gcloud project
gcloud config set project ${GCLOUD_PROJECT_ID}

# Start emulator
gcloud beta emulators firestore start --host-port=localhost:8200
